### ISSUE TITLE
Pretrained Model not Found

### ISSUE THREAD

**Issue by Ahmer-444** [jiweibo/SVHN-Multi-Digit-Recognition#2]
The link you shared, haven't any model there or may be the link is outdated.
Can you please share the pre-trained model link, it will really help.
Thanks

**Comment by jiweibo** [comment]
The link is valid, If you can not open it. I can send it to your email.

https://pan.baidu.com/s/1miR8j4s
password is crdf

**Comment by AlexBlack2202** [comment]
@jiweibo  can you send the pre-train model for me. I can not download the model from baidu. my email is pdtg50@yahoo.com.vn. Many thanks.

**Comment by jiweibo** [comment]
> @jiweibo can you send the pre-train model for me. I can not download the model from baidu. my email is [pdtg50@yahoo.com.vn](mailto:pdtg50@yahoo.com.vn). Many thanks.

I'm on a business trip. I'll give it to you when I get back in a week.

**Comment by AlexBlack2202** [comment]
> > @jiweibo can you send the pre-train model for me. I can not download the model from baidu. my email is [pdtg50@yahoo.com.vn](mailto:pdtg50@yahoo.com.vn). Many thanks.
> 
> I'm on a business trip. I'll give it to you when I get back in a week.

Thank you very much @jiweibo .
